---
- name: copy zabbix ethernet check script
  copy: 
    src: files/ethernet/zabbix-ethernet.sh
    dest: /usr/local/bin/zabbix-ethernet.sh
    owner: root
    mode: 750
- name: copy zabbix ethernet config file
  copy: 
    src: files/ethernet/zabbix-ethernet.conf
    dest: /etc/zabbix/zabbix_agentd.d/zabbix-ethernet.conf
    owner: root
    mode: 750
- name: restart zabbix-agent service
  service:
    name: zabbix-agent
    enabled: yes
    state: restarted
